
'use client';

import Image from "next/image";
import { notFound, useSearchParams } from "next/navigation";
import {
  CheckCircle,
  Tag,
  Download,
  ShoppingCart,
  Copy,
} from "lucide-react";
import { useMemo, useEffect, useState } from 'react';

import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import {
  Card,
  CardContent,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import Link from "next/link";
import { ImageCompareSlider } from "@/components/image-compare-slider";
import { useDoc } from "@/firebase/firestore/use-doc";
import { useCollection } from "@/firebase/firestore/use-collection";
import { doc, collection, query } from "firebase/firestore";
import { useFirestore } from "@/firebase/provider";
import type { Product, UserProfile, Software } from "@/lib/data";
import { Skeleton } from "@/components/ui/skeleton";
import { Button } from "@/components/ui/button";
import { useUser } from "@/firebase/auth/use-user";
import { useToast } from "@/hooks/use-toast";

function ProductPageClientButtons({
  price,
  productId,
  productName,
}: {
  price: number;
  productId: string;
  productName: string;
}) {
  const { user, loading: userLoading } = useUser();
  const firestore = useFirestore();
  const [formattedPrice, setFormattedPrice] = useState<string>("");
  const { toast } = useToast();
  
  const searchParams = useSearchParams();
  const ref = searchParams.get('ref');

  const userProfileRef = useMemo(() => {
    if (!user) return null;
    return doc(firestore, 'users', user.uid);
  }, [user, firestore]);
  const { data: userProfile, loading: profileLoading } = useDoc<UserProfile>(userProfileRef);

  useEffect(() => {
    const formatCurrency = (amount: number) => {
      return new Intl.NumberFormat("id-ID", {
        style: "currency",
        currency: "IDR",
        minimumFractionDigits: 0,
      }).format(amount);
    };
    setFormattedPrice(formatCurrency(price));
  }, [price]);
  
  useEffect(() => {
    // If a referral code is in the URL, store it in session storage.
    if (ref) {
      sessionStorage.setItem('affiliate_ref', ref);
    }
  }, [ref]);

  const getCheckoutUrl = () => {
    if (userLoading) return "#";
    
    // Always check session storage for the ref ID.
    const storedRef = sessionStorage.getItem('affiliate_ref');
    const refQueryParam = storedRef ? `&ref=${storedRef}` : '';
    
    let url = `/checkout?productId=${productId}${refQueryParam}`;
    
    if (user) {
      return url;
    }
    
    // If not logged in, redirect to login, but carry over the checkout and ref params.
    return `/login?redirect=${encodeURIComponent(url)}`;
  };

  const copyAffiliateLink = () => {
    // An affiliate link should only be generated by a logged-in affiliate user.
    if (!userProfile?.isAffiliate || !user) {
       toast({
        variant: "destructive",
        title: "Akses Ditolak",
        description: "Anda harus menjadi mitra afiliasi untuk membuat tautan.",
      });
      return;
    }
    const link = `${window.location.origin}/product/${productId}?ref=${user.uid}`;
    navigator.clipboard.writeText(link);
    toast({
      title: "Tautan Afiliasi Disalin",
      description: `Bagikan tautan untuk produk "${productName}" dan dapatkan komisi!`,
    });
  };

  const loading = userLoading || profileLoading;

  return (
    <>
      <div className="text-3xl font-bold text-primary">{formattedPrice}</div>
      <div className="flex flex-col sm:flex-row gap-2">
        <Button size="lg" className="w-full sm:w-auto" asChild disabled={loading}>
            <Link href={getCheckoutUrl()}>
                <ShoppingCart className="mr-2 h-4 w-4" /> 
                {loading ? "Memuat..." : "Beli Sekarang"}
            </Link>
        </Button>
        {userProfile?.isAffiliate && (
          <Button size="lg" variant="outline" className="w-full sm:w-auto" onClick={copyAffiliateLink} disabled={loading}>
            <Copy className="mr-2 h-4 w-4" />
            Buat Tautan Afiliasi
          </Button>
        )}
      </div>
    </>
  );
}


export function ProductPageContent({ productId }: { productId: string }) {
  const firestore = useFirestore();
  
  const productRef = useMemo(() => {
    if (!firestore || !productId) return null;
    return doc(firestore, 'products', productId);
  }, [firestore, productId]);

  const { data: product, loading: productLoading } = useDoc<Product>(productRef);

  const creatorRef = useMemo(() => {
      if (!firestore || !product?.creatorId) return null;
      return doc(firestore, 'users', product.creatorId);
  }, [firestore, product?.creatorId]);

  const { data: creator, loading: creatorLoading } = useDoc<UserProfile>(creatorRef);

  const softwareQuery = useMemo(() => {
    if (!firestore) return null;
    return query(collection(firestore, 'software'));
  }, [firestore]);

  const { data: softwareList, loading: softwareLoading } = useCollection<Software>(softwareQuery);

  const compatibleSoftwareDetails = useMemo(() => {
    if (!product || !softwareList) return [];
    return product.compatibleSoftware
        .map(name => softwareList.find(s => s.name === name))
        .filter((s): s is Software => !!s);
  }, [product, softwareList]);


  if (productLoading || creatorLoading || softwareLoading) {
    return (
        <div className="container mx-auto px-4 py-6">
            <div className="grid md:grid-cols-2 gap-4 lg:gap-6">
                <div>
                    <Skeleton className="aspect-[3/2] w-full rounded-lg" />
                </div>
                <div className="flex flex-col gap-4">
                    <Skeleton className="h-8 w-3/4" />
                    <div className="flex items-center gap-2">
                        <Skeleton className="h-8 w-8 rounded-full" />
                        <Skeleton className="h-5 w-24" />
                    </div>
                    <Skeleton className="h-20 w-full" />
                    <Skeleton className="h-8 w-32" />
                    <Skeleton className="h-10 w-48" />
                    <Skeleton className="h-28 w-full" />
                </div>
            </div>
        </div>
    );
  }

  if (!product) {
    // This will trigger the not-found.tsx file
    notFound();
  }

  return (
    <div className="container mx-auto px-4 py-6">
      <div className="grid md:grid-cols-2 gap-4 lg:gap-6">
        <div>
          <ImageCompareSlider
            beforeImage={{ imageUrl: product.imageBeforeUrl, imageHint: product.imageBeforeHint, description: product.name }}
            afterImage={{ imageUrl: product.imageAfterUrl, imageHint: product.imageAfterHint, description: product.name }}
            className="aspect-[3/2] rounded-lg overflow-hidden"
          />
        </div>

        <div className="flex flex-col gap-3">
          <div>
            <h1 className="text-2xl md:text-3xl font-bold tracking-tight font-headline">
              {product.name}
            </h1>
            {creator && (
                 <div className="mt-2 flex items-center gap-3">
                    <Link href={`/creator/${creator.slug}`} className="flex items-center gap-2 group">
                        <Avatar className="h-8 w-8">
                            <AvatarImage src={creator.avatarUrl} data-ai-hint={creator.avatarHint} />
                            <AvatarFallback>{creator.name.charAt(0)}</AvatarFallback>
                        </Avatar>
                        <span className="font-medium text-sm group-hover:text-primary transition-colors">{creator.name}</span>
                    </Link>
                </div>
            )}
          </div>
          <p className="text-base text-muted-foreground">{product.description}</p>
          
          <ProductPageClientButtons price={product.price} productId={product.id} productName={product.name} />

          <Card className="rounded-lg">
            <CardContent className="pt-4 grid gap-3 text-sm">
                {compatibleSoftwareDetails && compatibleSoftwareDetails.length > 0 && (
                    <div className="flex items-center gap-2">
                        <CheckCircle className="h-4 w-4 text-primary flex-shrink-0"/>
                        <div className="flex flex-wrap items-center gap-x-3 gap-y-1">
                            <span className="font-medium">Kompatibel dengan:</span>
                            {compatibleSoftwareDetails.map(s => (
                                <div key={s.id} className="flex items-center gap-1.5 text-muted-foreground">
                                    {s.icon ? (
                                        <img src={s.icon} alt={`${s.name} icon`} className="h-4 w-4 object-contain" />
                                    ) : <div className="h-4 w-4 bg-muted rounded-sm" />}
                                    <span>{s.name}</span>
                                </div>
                            ))}
                        </div>
                    </div>
                )}
                <div className="flex items-center gap-2">
                    <Download className="h-4 w-4 text-primary"/>
                    <span>Unduhan digital instan</span>
                </div>
                {product.tags && product.tags.length > 0 && (
                    <div className="flex items-center gap-2">
                        <Tag className="h-4 w-4 text-primary"/>
                        <div className="flex flex-wrap gap-1">
                        {product.tags.map(tag => <Badge key={tag} variant="secondary">{tag}</Badge>)}
                        </div>
                    </div>
                )}
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
